"""baseline

Revision ID: 0001
Revises: 
Create Date: 2026-10-03 09:44:09.930782
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('credits_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_api_key'), ['api_key'], unique=False)

    op.create_table('accountplan',
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plan', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('apikey',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prefix', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('last_used_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('revoked_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('apikey', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_apikey_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_apikey_key_hash'), ['key_hash'], unique=True)

    op.create_table('auditlog',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auditlog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auditlog_account_id'), ['account_id'], unique=False)

    op.create_table('consentchallenge',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('replica_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phrase', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consentchallenge', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consentchallenge_replica_id'), ['replica_id'], unique=False)

    op.create_table('consentrecord',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('replica_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('speaker_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phrase', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transcript', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('audio_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('audio_sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('verified_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consentrecord', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consentrecord_replica_id'), ['replica_id'], unique=False)

    op.create_table('consentverification',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('consent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('replica_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('audio_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('audio_sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transcript', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phrase_score', sa.Float(), nullable=False),
    sa.Column('code_words_ok', sa.Boolean(), nullable=False),
    sa.Column('voice_score', sa.Float(), nullable=True),
    sa.Column('voice_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consentverification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consentverification_consent_id'), ['consent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consentverification_replica_id'), ['replica_id'], unique=False)

    op.create_table('conversation',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('persona_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('room_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('ended_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('seconds_used', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_account_id'), ['account_id'], unique=False)

    op.create_table('conversationmeta',
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('persona_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('participant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('context', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('variables', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('max_seconds', sa.Integer(), nullable=True),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('share_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('finalized_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('end_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_closed_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    with op.batch_alter_table('conversationmeta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversationmeta_account_id'), ['account_id'], unique=False)

    op.create_table('conversationmetric',
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('persona_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_turns', sa.Integer(), nullable=False),
    sa.Column('agent_turns', sa.Integer(), nullable=False),
    sa.Column('avg_first_audio_ms', sa.Float(), nullable=True),
    sa.Column('p95_first_audio_ms', sa.Float(), nullable=True),
    sa.Column('interruptions', sa.Integer(), nullable=False),
    sa.Column('tool_calls', sa.Integer(), nullable=False),
    sa.Column('guardrail_hits', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    with op.batch_alter_table('conversationmetric', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversationmetric_account_id'), ['account_id'], unique=False)

    op.create_table('datadeletion',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('files_removed', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('datadeletion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_datadeletion_account_id'), ['account_id'], unique=False)

    op.create_table('jobclaim',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ref_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('locked_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('finished_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('jobclaim', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobclaim_ref_id'), ['ref_id'], unique=False)

    op.create_table('knowledgechunk',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('doc_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('persona_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('embedding', sa.LargeBinary(), nullable=True),
    sa.Column('embed_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledgechunk', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledgechunk_doc_id'), ['doc_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledgechunk_persona_id'), ['persona_id'], unique=False)

    op.create_table('knowledgedoc',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('persona_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('n_chunks', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledgedoc', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledgedoc_persona_id'), ['persona_id'], unique=False)

    op.create_table('ledgerentry',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seconds', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ledgerentry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledgerentry_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledgerentry_ref'), ['ref'], unique=True)

    op.create_table('listeningclip',
    sa.Column('replica_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duration_s', sa.Float(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('fps', sa.Float(), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('replica_id')
    )
    op.create_table('memoryscope',
    sa.Column('memory_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('persona_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('participant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('memory_id')
    )
    with op.batch_alter_table('memoryscope', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memoryscope_participant_id'), ['participant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memoryscope_persona_id'), ['persona_id'], unique=False)

    op.create_table('memorysummary',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('persona_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memorysummary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memorysummary_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memorysummary_persona_id'), ['persona_id'], unique=False)

    op.create_table('objectiveprogress',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('evidence', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('variables', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('completed_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('objectiveprogress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_objectiveprogress_conversation_id'), ['conversation_id'], unique=False)

    op.create_table('paymentevent',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'event_id')
    )
    op.create_table('persona',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('system_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('replica_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('llm', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tts_voice', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('knowledge', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('persona', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_persona_account_id'), ['account_id'], unique=False)

    op.create_table('personaconfig',
    sa.Column('persona_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('greeting', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('objectives', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('guardrails', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('guardrail_fallback', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('memory_enabled', sa.Boolean(), nullable=False),
    sa.Column('llm_base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('llm_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('llm_api_key_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stt_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('persona_id')
    )
    with op.batch_alter_table('personaconfig', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_personaconfig_account_id'), ['account_id'], unique=False)

    op.create_table('personatool',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('persona_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parameters', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('webhook_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('secret_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timeout_s', sa.Float(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('personatool', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_personatool_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_personatool_persona_id'), ['persona_id'], unique=False)

    op.create_table('replica',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('train_video_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('replica', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_replica_account_id'), ['account_id'], unique=False)

    op.create_table('replicavoice',
    sa.Column('replica_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('consent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('engine', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ref_seconds', sa.Float(), nullable=False),
    sa.Column('ref_quality', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=True),
    sa.Column('wer', sa.Float(), nullable=True),
    sa.Column('synth_rtf', sa.Float(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('replica_id')
    )
    with op.batch_alter_table('replicavoice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_replicavoice_account_id'), ['account_id'], unique=False)

    op.create_table('sharelink',
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('persona_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('max_seconds', sa.Integer(), nullable=False),
    sa.Column('max_total_seconds', sa.Integer(), nullable=False),
    sa.Column('max_sessions_per_hour', sa.Integer(), nullable=False),
    sa.Column('max_sessions_per_ip_hour', sa.Integer(), nullable=False),
    sa.Column('used_seconds', sa.Integer(), nullable=False),
    sa.Column('sessions_started', sa.Integer(), nullable=False),
    sa.Column('expires_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('revoked_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    with op.batch_alter_table('sharelink', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sharelink_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sharelink_persona_id'), ['persona_id'], unique=False)

    op.create_table('sharesession',
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('allowed_seconds', sa.Integer(), nullable=False),
    sa.Column('started_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('counted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    with op.batch_alter_table('sharesession', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sharesession_token'), ['token'], unique=False)

    op.create_table('toolcalllog',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tool_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('arguments', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('result', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('toolcalllog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_toolcalllog_conversation_id'), ['conversation_id'], unique=False)

    op.create_table('transcriptturn',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('t_ms', sa.Integer(), nullable=False),
    sa.Column('first_audio_ms', sa.Integer(), nullable=True),
    sa.Column('interrupted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transcriptturn', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transcriptturn_conversation_id'), ['conversation_id'], unique=False)

    op.create_table('video',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('replica_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('script', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('output_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_video_account_id'), ['account_id'], unique=False)

    op.create_table('videobatch',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('replica_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('videobatch', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_videobatch_account_id'), ['account_id'], unique=False)

    op.create_table('videobatchitem',
    sa.Column('video_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('batch_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('variables', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rendered_script', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('video_id')
    )
    with op.batch_alter_table('videobatchitem', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_videobatchitem_batch_id'), ['batch_id'], unique=False)

    op.create_table('videometa',
    sa.Column('video_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('callback_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('voice', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('webhook_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('video_id')
    )
    op.create_table('webhookdelivery',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('endpoint_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('last_status_code', sa.Integer(), nullable=True),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('delivered_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhookdelivery', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhookdelivery_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhookdelivery_endpoint_id'), ['endpoint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhookdelivery_next_attempt_at'), ['next_attempt_at'], unique=False)

    op.create_table('webhookendpoint',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('secret', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('events', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhookendpoint', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhookendpoint_account_id'), ['account_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhookendpoint', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhookendpoint_account_id'))

    op.drop_table('webhookendpoint')
    with op.batch_alter_table('webhookdelivery', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhookdelivery_next_attempt_at'))
        batch_op.drop_index(batch_op.f('ix_webhookdelivery_endpoint_id'))
        batch_op.drop_index(batch_op.f('ix_webhookdelivery_account_id'))

    op.drop_table('webhookdelivery')
    op.drop_table('videometa')
    with op.batch_alter_table('videobatchitem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_videobatchitem_batch_id'))

    op.drop_table('videobatchitem')
    with op.batch_alter_table('videobatch', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_videobatch_account_id'))

    op.drop_table('videobatch')
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_video_account_id'))

    op.drop_table('video')
    with op.batch_alter_table('transcriptturn', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transcriptturn_conversation_id'))

    op.drop_table('transcriptturn')
    with op.batch_alter_table('toolcalllog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_toolcalllog_conversation_id'))

    op.drop_table('toolcalllog')
    with op.batch_alter_table('sharesession', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sharesession_token'))

    op.drop_table('sharesession')
    with op.batch_alter_table('sharelink', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sharelink_persona_id'))
        batch_op.drop_index(batch_op.f('ix_sharelink_account_id'))

    op.drop_table('sharelink')
    with op.batch_alter_table('replicavoice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_replicavoice_account_id'))

    op.drop_table('replicavoice')
    with op.batch_alter_table('replica', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_replica_account_id'))

    op.drop_table('replica')
    with op.batch_alter_table('personatool', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_personatool_persona_id'))
        batch_op.drop_index(batch_op.f('ix_personatool_account_id'))

    op.drop_table('personatool')
    with op.batch_alter_table('personaconfig', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_personaconfig_account_id'))

    op.drop_table('personaconfig')
    with op.batch_alter_table('persona', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_persona_account_id'))

    op.drop_table('persona')
    op.drop_table('paymentevent')
    with op.batch_alter_table('objectiveprogress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_objectiveprogress_conversation_id'))

    op.drop_table('objectiveprogress')
    with op.batch_alter_table('memorysummary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memorysummary_persona_id'))
        batch_op.drop_index(batch_op.f('ix_memorysummary_conversation_id'))

    op.drop_table('memorysummary')
    with op.batch_alter_table('memoryscope', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memoryscope_persona_id'))
        batch_op.drop_index(batch_op.f('ix_memoryscope_participant_id'))

    op.drop_table('memoryscope')
    op.drop_table('listeningclip')
    with op.batch_alter_table('ledgerentry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledgerentry_ref'))
        batch_op.drop_index(batch_op.f('ix_ledgerentry_account_id'))

    op.drop_table('ledgerentry')
    with op.batch_alter_table('knowledgedoc', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledgedoc_persona_id'))

    op.drop_table('knowledgedoc')
    with op.batch_alter_table('knowledgechunk', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledgechunk_persona_id'))
        batch_op.drop_index(batch_op.f('ix_knowledgechunk_doc_id'))

    op.drop_table('knowledgechunk')
    with op.batch_alter_table('jobclaim', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobclaim_ref_id'))

    op.drop_table('jobclaim')
    with op.batch_alter_table('datadeletion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_datadeletion_account_id'))

    op.drop_table('datadeletion')
    with op.batch_alter_table('conversationmetric', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversationmetric_account_id'))

    op.drop_table('conversationmetric')
    with op.batch_alter_table('conversationmeta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversationmeta_account_id'))

    op.drop_table('conversationmeta')
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_account_id'))

    op.drop_table('conversation')
    with op.batch_alter_table('consentverification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consentverification_replica_id'))
        batch_op.drop_index(batch_op.f('ix_consentverification_consent_id'))

    op.drop_table('consentverification')
    with op.batch_alter_table('consentrecord', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consentrecord_replica_id'))

    op.drop_table('consentrecord')
    with op.batch_alter_table('consentchallenge', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consentchallenge_replica_id'))

    op.drop_table('consentchallenge')
    with op.batch_alter_table('auditlog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditlog_account_id'))

    op.drop_table('auditlog')
    with op.batch_alter_table('apikey', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_apikey_key_hash'))
        batch_op.drop_index(batch_op.f('ix_apikey_account_id'))

    op.drop_table('apikey')
    op.drop_table('accountplan')
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_api_key'))

    op.drop_table('account')
    # ### end Alembic commands ###
