"""platform and feature tables

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-03 10:15:32.624592
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billingsettings',
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('overage_enabled', sa.Boolean(), nullable=False),
    sa.Column('overage_cap_cents', sa.Integer(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('creativeasset',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ext', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('creativeasset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_creativeasset_account_id'), ['account_id'], unique=False)

    op.create_table('overagecharge',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('period', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seconds', sa.Integer(), nullable=False),
    sa.Column('amount_millicents', sa.Integer(), nullable=False),
    sa.Column('rate_cents_per_min', sa.Integer(), nullable=False),
    sa.Column('ref', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('overagecharge', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_overagecharge_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_overagecharge_period'), ['period'], unique=False)
        batch_op.create_index(batch_op.f('ix_overagecharge_ref'), ['ref'], unique=True)

    op.create_table('perceptionconfig',
    sa.Column('persona_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('consent_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('require_user_consent', sa.Boolean(), nullable=False),
    sa.Column('camera', sa.Boolean(), nullable=False),
    sa.Column('screen', sa.Boolean(), nullable=False),
    sa.Column('store_frames', sa.Boolean(), nullable=False),
    sa.Column('vlm_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('interval_s', sa.Float(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('persona_id')
    )
    with op.batch_alter_table('perceptionconfig', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_perceptionconfig_account_id'), ['account_id'], unique=False)

    op.create_table('photoreplica',
    sa.Column('replica_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('photo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('idle_seconds', sa.Float(), nullable=False),
    sa.Column('head_motion', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('warnings', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('animate_s', sa.Float(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('replica_id')
    )
    op.create_table('replicabackground',
    sa.Column('replica_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('spec', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('replica_id')
    )
    op.create_table('videooptions',
    sa.Column('video_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('options', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('video_id')
    )
    op.create_table('workspace',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workspace', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspace_owner_account_id'), ['owner_account_id'], unique=False)

    op.create_table('workspaceinvite',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('invited_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('accepted_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('revoked_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workspaceinvite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspaceinvite_token_hash'), ['token_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspaceinvite_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('workspacemember',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'account_id')
    )
    with op.batch_alter_table('workspacemember', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspacemember_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspacemember_workspace_id'), ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspacemember', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspacemember_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_workspacemember_account_id'))

    op.drop_table('workspacemember')
    with op.batch_alter_table('workspaceinvite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspaceinvite_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_workspaceinvite_token_hash'))

    op.drop_table('workspaceinvite')
    with op.batch_alter_table('workspace', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspace_owner_account_id'))

    op.drop_table('workspace')
    op.drop_table('videooptions')
    op.drop_table('replicabackground')
    op.drop_table('photoreplica')
    with op.batch_alter_table('perceptionconfig', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_perceptionconfig_account_id'))

    op.drop_table('perceptionconfig')
    with op.batch_alter_table('overagecharge', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_overagecharge_ref'))
        batch_op.drop_index(batch_op.f('ix_overagecharge_period'))
        batch_op.drop_index(batch_op.f('ix_overagecharge_account_id'))

    op.drop_table('overagecharge')
    with op.batch_alter_table('creativeasset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creativeasset_account_id'))

    op.drop_table('creativeasset')
    op.drop_table('billingsettings')
    # ### end Alembic commands ###
