"""competitor gap tables

Revision ID: 0003
Revises: bf0dad20d4dc
Create Date: 2026-10-04 01:36:32.792930
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = '0003'
down_revision = 'bf0dad20d4dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversationinsight',
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('persona_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sentiment', sa.Float(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trend', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('topics', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_words', sa.Integer(), nullable=False),
    sa.Column('agent_words', sa.Integer(), nullable=False),
    sa.Column('questions', sa.Integer(), nullable=False),
    sa.Column('interruptions', sa.Integer(), nullable=False),
    sa.Column('turn_sentiments', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    with op.batch_alter_table('conversationinsight', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversationinsight_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversationinsight_persona_id'), ['persona_id'], unique=False)

    op.create_table('knowledgesource',
    sa.Column('doc_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('persona_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fetched_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('doc_id')
    )
    with op.batch_alter_table('knowledgesource', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledgesource_persona_id'), ['persona_id'], unique=False)

    op.create_table('pronunciationentry',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('persona_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('term', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('replacement', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('case_sensitive', sa.Boolean(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pronunciationentry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pronunciationentry_persona_id'), ['persona_id'], unique=False)

    op.create_table('shareschedule',
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('starts_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('ends_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('invitee_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('invitee_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    with op.batch_alter_table('shareschedule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shareschedule_account_id'), ['account_id'], unique=False)

    op.create_table('turncitation',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('doc_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('snippet', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('turncitation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_turncitation_conversation_id'), ['conversation_id'], unique=False)

    op.create_table('voicetuning',
    sa.Column('persona_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('interruption_sensitivity', sa.Float(), nullable=False),
    sa.Column('allow_interruptions', sa.Boolean(), nullable=False),
    sa.Column('turn_patience_ms', sa.Integer(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('persona_id')
    )
    with op.batch_alter_table('voicetuning', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voicetuning_account_id'), ['account_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voicetuning', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voicetuning_account_id'))

    op.drop_table('voicetuning')
    with op.batch_alter_table('turncitation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_turncitation_conversation_id'))

    op.drop_table('turncitation')
    with op.batch_alter_table('shareschedule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shareschedule_account_id'))

    op.drop_table('shareschedule')
    with op.batch_alter_table('pronunciationentry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pronunciationentry_persona_id'))

    op.drop_table('pronunciationentry')
    with op.batch_alter_table('knowledgesource', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledgesource_persona_id'))

    op.drop_table('knowledgesource')
    with op.batch_alter_table('conversationinsight', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversationinsight_persona_id'))
        batch_op.drop_index(batch_op.f('ix_conversationinsight_account_id'))

    op.drop_table('conversationinsight')
    # ### end Alembic commands ###
