"""wave 2 tables: creative, voice, perception, platform, safety, templates, leads, widgets

Revision ID: bf0dad20d4dc
Revises: 0002
Create Date: 2026-10-03 19:33:27.419053
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = 'bf0dad20d4dc'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apikeyscope',
    sa.Column('key_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('key_id')
    )
    op.create_table('facebinding',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('consent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('replica_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recording_sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ref_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('face_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('face_score', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('frames_used', sa.Integer(), nullable=False),
    sa.Column('live_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('live_nonrigid', sa.Float(), nullable=True),
    sa.Column('live_mouth', sa.Float(), nullable=True),
    sa.Column('live_texture', sa.Float(), nullable=True),
    sa.Column('live_residual', sa.Float(), nullable=True),
    sa.Column('live_reasons', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('facebinding', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_facebinding_consent_id'), ['consent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_facebinding_replica_id'), ['replica_id'], unique=False)

    op.create_table('lead',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('persona_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('interest', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extra', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('consent', sa.Boolean(), nullable=False),
    sa.Column('consent_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lead_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_persona_id'), ['persona_id'], unique=False)

    op.create_table('leadcaptureconfig',
    sa.Column('persona_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('required_fields', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('require_consent', sa.Boolean(), nullable=False),
    sa.Column('disclosure', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('persona_id')
    )
    with op.batch_alter_table('leadcaptureconfig', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leadcaptureconfig_account_id'), ['account_id'], unique=False)

    op.create_table('personaintegration',
    sa.Column('persona_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('booking_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('booking_secret_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notify_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notify_secret_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('persona_id')
    )
    with op.batch_alter_table('personaintegration', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_personaintegration_account_id'), ['account_id'], unique=False)

    op.create_table('templateinstance',
    sa.Column('persona_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('template_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('template_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('persona_id')
    )
    with op.batch_alter_table('templateinstance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_templateinstance_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_templateinstance_template_id'), ['template_id'], unique=False)

    op.create_table('widgetconfig',
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('persona_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('allowed_domains', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('greeting', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    with op.batch_alter_table('widgetconfig', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_widgetconfig_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_widgetconfig_persona_id'), ['persona_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('widgetconfig', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_widgetconfig_persona_id'))
        batch_op.drop_index(batch_op.f('ix_widgetconfig_account_id'))

    op.drop_table('widgetconfig')
    with op.batch_alter_table('templateinstance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_templateinstance_template_id'))
        batch_op.drop_index(batch_op.f('ix_templateinstance_account_id'))

    op.drop_table('templateinstance')
    with op.batch_alter_table('personaintegration', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_personaintegration_account_id'))

    op.drop_table('personaintegration')
    with op.batch_alter_table('leadcaptureconfig', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leadcaptureconfig_account_id'))

    op.drop_table('leadcaptureconfig')
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_persona_id'))
        batch_op.drop_index(batch_op.f('ix_lead_created_at'))
        batch_op.drop_index(batch_op.f('ix_lead_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_lead_account_id'))

    op.drop_table('lead')
    with op.batch_alter_table('facebinding', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_facebinding_replica_id'))
        batch_op.drop_index(batch_op.f('ix_facebinding_consent_id'))

    op.drop_table('facebinding')
    op.drop_table('apikeyscope')
    # ### end Alembic commands ###
